# Copyright (C) 2018 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).
name: mapnet_release
channels:
- pytorch
dependencies:
- configparser
- ipython
- numpy
- pip
- python=2.7
- scikit-learn
- scipy
- pytorch
- torchvision
- matplotlib
- pip:
  - colour-demosaicing
  - transforms3d
  - visdom
